export const ERROR_CODES = {
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  DEPOSIT_REQUIRED: 'DEPOSIT_REQUIRED',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUCTION_NOT_ACTIVE: 'AUCTION_NOT_ACTIVE',
  AUCTION_ENDED: 'AUCTION_ENDED',
  BID_TOO_LOW: 'BID_TOO_LOW',
  SELF_BID_FORBIDDEN: 'SELF_BID_FORBIDDEN',
} as const;

export const SOFT_CLOSE_WINDOW_MS = 2 * 60 * 1000; // 2 minutes
export const SOFT_CLOSE_EXTENSION_MS = 2 * 60 * 1000; // Extend by 2 minutes
