/**
 * POST /api/upload
 *
 * Stores an uploaded image in Firebase Storage and returns the public URL.
 *
 * Request: multipart/form-data
 *   - file : File   — the image to upload (required)
 *   - type : string — 'auction' | 'chat' (optional, default: 'auction')
 *
 * Response: { url: string }
 *
 * Limits & validation:
 *   - auction images: max 4 MB
 *   - chat attachments: max 2 MB
 *   - actual bytes must match one of: JPEG, PNG, WebP, GIF (magic-byte check —
 *     the client-supplied Content-Type is not trusted)
 */

import { auth } from '@/lib/auth';
import { adminStorage } from '@/lib/firebase-admin';
import { NextRequest, NextResponse } from 'next/server';
import { v4 as uuidv4 } from 'uuid';
import { detectImageMime, SUPPORTED_IMAGE_MIMES } from '@/lib/image-sniff';
import { moderateImage } from '@/lib/image-moderation';
import { apiLimiter } from '@/lib/ratelimit';
import { log } from '@/lib/logger';

const LIMITS = {
  auction: 4 * 1024 * 1024,  // 4 MB
  chat:    2 * 1024 * 1024,  // 2 MB
} as const;

// Map detected MIME -> canonical extension. Never trust file.name.
const MIME_TO_EXT: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png':  'png',
  'image/webp': 'webp',
  'image/gif':  'gif',
};

function sanitizeFilenameForStorage(name: unknown): string {
  if (typeof name !== 'string') return '';
  // Drop control chars and HTML-significant chars before truncation.
   
  return name.replace(/[\x00-\x1f\x7f<>"'`]/g, '').slice(0, 256);
}

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Per-user rate limit. Without this a single account can OOM the storage
  // budget by uploading thousands of files in a tight loop.
  const gate = await apiLimiter.limit(`upload_${session.user.id}`);
  if (!gate.success) {
    return NextResponse.json({ error: 'Too many uploads. Please slow down.' }, { status: 429 });
  }

  let formData: FormData;
  try {
    formData = await req.formData();
  } catch {
    return NextResponse.json({ error: 'Invalid form data' }, { status: 400 });
  }

  const file = formData.get('file') as File | null;
  const rawType = formData.get('type');
  const type: 'auction' | 'chat' = rawType === 'chat' ? 'chat' : 'auction';

  if (!file) {
    return NextResponse.json({ error: 'No file provided' }, { status: 400 });
  }

  const maxSize = LIMITS[type];
  if (file.size > maxSize) {
    return NextResponse.json(
      { error: `File too large. Max ${maxSize / 1024 / 1024} MB for ${type} uploads.` },
      { status: 400 },
    );
  }
  if (file.size === 0) {
    return NextResponse.json({ error: 'Empty file' }, { status: 400 });
  }

  // Read once, validate against actual bytes, then upload the same buffer.
  const buffer = Buffer.from(await file.arrayBuffer());
  const detectedMime = detectImageMime(buffer);
  if (!detectedMime) {
    return NextResponse.json(
      { error: `File contents are not a valid ${SUPPORTED_IMAGE_MIMES.join(', ')} image` },
      { status: 400 },
    );
  }

  // SafeSearch — auto-no-ops if IMAGE_MODERATION env var isn't set.
  const moderation = await moderateImage(buffer);
  if (!moderation.allowed) {
    log.warn('[Upload] Rejected by SafeSearch', {
      userId: session.user.id, reason: moderation.reason, scores: moderation.scores,
    });
    return NextResponse.json(
      { error: 'This image violates our content policy and cannot be uploaded.' },
      { status: 422 },
    );
  }

  try {
    const ext      = MIME_TO_EXT[detectedMime];
    const folder   = type === 'chat' ? 'chat' : 'auctions';
    const filename = `${folder}/${session.user.id}/${uuidv4()}.${ext}`;
    const bucket   = adminStorage.bucket();
    const fileRef  = bucket.file(filename);

    await fileRef.save(buffer, {
      metadata: {
        contentType:  detectedMime,
        cacheControl: 'public, max-age=31536000, immutable',
        metadata: {
          uploadedBy:   session.user.id,
          uploadedFor:  type,
          uploadedAtMs: String(Date.now()),
          // Sanitised — control chars and HTML-significant chars stripped before
          // storage so the value can never become an injection vector.
          originalName: sanitizeFilenameForStorage(file.name),
        },
      },
    });

    // Both auction and chat uploads are served via signed URLs or public URLs.
    // We use CDN-cacheable Firebase Storage URLs for auctions so the client
    // can dynamically fetch the _400x400 WebP thumbnails generated by the Firebase Extension.
    // Chat attachments remain strictly private via short-lived signed URLs.
    let url: string;
    
    if (type === 'auction') {
      url = `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(fileRef.name)}?alt=media`;
    } else {
      const expiresMs = Date.now() + 7 * 24 * 60 * 60 * 1000;
      [url] = await fileRef.getSignedUrl({ action: 'read', expires: expiresMs });
    }

    return NextResponse.json({ url });
  } catch (error) {
    log.error('[Upload] Firebase Storage error', error, { area: 'upload', severity: 'warning' });
    return NextResponse.json({ error: 'Upload failed. Please try again.' }, { status: 500 });
  }
}
